using System.Reflection;
using System.Text.RegularExpressions;
using CodeShellManager.Terminal;
using Xunit;

namespace CodeShellManager.Tests;

/// <summary>
/// Tests for the ANSI-stripping regex used by <see cref="OutputIndexer"/> before
/// feeding lines into the FTS5 index. The regex is a <c>private static partial</c>
/// method generated by <c>[GeneratedRegex]</c>, so it's reached via reflection.
///
/// The pattern (as of writing) is:
/// <code>
/// \x1B\[[?0-9;]*[mGKHFJABCDsuhl]   // CSI: ESC[ ... final-byte
/// | \x1B\].*?(?:\x07|\x1B\\)        // OSC: ESC] ... BEL or ESC\ (ST)
/// | \x1B[=>]                        // DECKPAM / DECKPNM (ESC= / ESC>)
/// | \r                              // carriage return
/// </code>
///
/// Note: this regex deliberately handles only the subset of ANSI control sequences
/// that ConPTY + xterm.js commonly emit. CSI sequences whose final byte is outside
/// <c>[mGKHFJABCDsuhl]</c> (for example DEC private-mode <c>n</c>, <c>r</c>, <c>t</c>,
/// or device-status reports) are intentionally left in the indexed text.
///
/// String-literal note: ESC and BEL are written as <c></c> / <c></c>
/// (fixed 4-digit form). The variable-length <c>\x</c> escape would greedily eat
/// any hex letter that follows (e.g. <c>"\x1Bb"</c> parses as the single
/// character <c>U+01BB</c>, not ESC + 'b').
/// </summary>
public class OutputIndexerTests
{
    private const string ESC = "";
    private const string BEL = "";

    private static readonly Regex Ansi = InvokeAnsiPattern();

    private static Regex InvokeAnsiPattern()
    {
        var mi = typeof(OutputIndexer).GetMethod(
            "AnsiPattern",
            BindingFlags.NonPublic | BindingFlags.Static);
        Assert.NotNull(mi);
        var rx = (Regex?)mi!.Invoke(null, null);
        Assert.NotNull(rx);
        return rx!;
    }

    private static string Strip(string input) => Ansi.Replace(input, "");

    [Fact]
    public void Strip_BasicCsiColor_RemovesEscapes()
    {
        Assert.Equal("red", Strip($"{ESC}[31mred{ESC}[0m"));
    }

    [Fact]
    public void Strip_CsiWithMultipleParameters_RemovesEscapes()
    {
        Assert.Equal("bold green", Strip($"{ESC}[1;32mbold green{ESC}[0m"));
    }

    [Fact]
    public void Strip_CsiCursorMotion_ClearScreenAndHome_AreRemoved()
    {
        // ESC[2J = clear screen, ESC[H = cursor home
        Assert.Equal("", Strip($"{ESC}[2J{ESC}[H"));
    }

    [Fact]
    public void Strip_CsiCursorMovementSequences_AreRemoved()
    {
        // A/B/C/D = cursor up/down/forward/back, G = horizontal absolute,
        // K = erase in line, F = previous-line, s/u = save/restore cursor.
        var input = $"x{ESC}[2Ay{ESC}[3Bz{ESC}[4Cw{ESC}[5Dv{ESC}[10Gu{ESC}[Kt{ESC}[Fs{ESC}[sr{ESC}[uq";
        Assert.Equal("xyzwvutsrq", Strip(input));
    }

    [Fact]
    public void Strip_CsiPrivateMode_AltScreenAndBracketedPaste_AreRemoved()
    {
        // ESC[?1049h = enable alt screen, ESC[?2004h = bracketed paste on,
        // ESC[?2004l = bracketed paste off. The `?` is matched by [?0-9;]*.
        Assert.Equal("body", Strip($"{ESC}[?1049h{ESC}[?2004hbody{ESC}[?2004l{ESC}[?1049l"));
    }

    [Fact]
    public void Strip_OscWithBelTerminator_RemovesSequence()
    {
        // Set window title: ESC]0;title BEL
        Assert.Equal("rest", Strip($"{ESC}]0;title{BEL}rest"));
    }

    [Fact]
    public void Strip_OscWithStringTerminator_RemovesSequence()
    {
        // String Terminator (ST) = ESC \. The regex's OSC arm accepts both BEL
        // and ESC\, so this should also be stripped.
        Assert.Equal("rest", Strip($"{ESC}]0;title{ESC}\\rest"));
    }

    [Fact]
    public void Strip_OscIsNonGreedy_DoesNotEatPastFirstTerminator()
    {
        // Two OSCs back-to-back: the non-greedy `.*?` should stop at the first BEL.
        Assert.Equal("middleend", Strip($"{ESC}]0;a{BEL}middle{ESC}]0;b{BEL}end"));
    }

    [Fact]
    public void Strip_CarriageReturn_IsRemoved()
    {
        Assert.Equal("ab", Strip("a\rb"));
    }

    [Fact]
    public void Strip_CarriageReturnPreservesNewline()
    {
        // CRLF -> LF (CR removed, LF kept). Feed() relies on this so that the
        // \n split produces clean lines without trailing \r.
        Assert.Equal("line1\nline2", Strip("line1\r\nline2"));
    }

    [Fact]
    public void Strip_KeypadModeEscapes_AreRemoved()
    {
        // ESC= (DECKPAM) and ESC> (DECKPNM) — two-byte escapes ConPTY uses.
        Assert.Equal("hello", Strip($"{ESC}=hel{ESC}>lo"));
    }

    [Fact]
    public void Strip_PlainText_IsUnchanged()
    {
        Assert.Equal("hello world", Strip("hello world"));
    }

    [Fact]
    public void Strip_EmptyInput_ReturnsEmpty()
    {
        Assert.Equal("", Strip(""));
    }

    [Fact]
    public void Strip_MixedAnsiAndPlain_RemovesOnlyEscapes()
    {
        var input = $"{ESC}[31mError:{ESC}[0m something {ESC}[1;33mwarning{ESC}[0m done";
        Assert.Equal("Error: something warning done", Strip(input));
    }

    [Fact]
    public void Strip_LeavesUnsupportedCsiFinalsIntact()
    {
        // Documenting current behavior: the regex's CSI arm only accepts finals
        // in [mGKHFJABCDsuhl]. A device-status query like ESC[6n (final 'n') is
        // NOT stripped. If the regex is later widened, update this test.
        var input = $"before{ESC}[6nafter";
        // The escape sequence remains intact because the CSI arm requires a
        // matching final byte that we don't list.
        Assert.Contains($"{ESC}[6n", Strip(input));
    }

    [Fact]
    public void Strip_LoneEscapeWithoutSequence_IsLeftAlone()
    {
        // A bare ESC with no [, ], =, or > following it is not matched by any
        // arm of the regex. Documenting that as intentional.
        Assert.Equal($"a{ESC}b", Strip($"a{ESC}b"));
    }
}
